name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Dar permisos Maven
        run: chmod +x mvnw

      - name: Compilar proyecto
        run: ./mvnw clean package -DskipTests

      - name: Analisis SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.projectKey=PatricioDuoc_proyecto_springboot_usuarios \
            -Dsonar.organization=patricioduoc \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Build Docker
        run: docker build -t springboot-devops .

      - name: Deploy Docker Compose
        run: docker compose up -d --build